<?xml version="1.0" encoding="utf-8"?><Database Name="longtt_ptpmud" Class="MyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql.bsite.net\MSSQL2016;Initial Catalog=longtt_ptpmud;User ID=longtt_ptpmud" SettingsObjectName="Project2.Properties.Settings" SettingsPropertyName="longtt_ptpmudConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="id" OtherKey="type_id" Type="Product" />
      <Association Name="Category_Product1" Member="Products1" ThisKey="id" OtherKey="brand_id" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Role_Employee" Member="Employees" ThisKey="id" OtherKey="role_id" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="City_Customer" Member="Customers" ThisKey="id" OtherKey="city_id" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="is_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="created_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="updated_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="id" OtherKey="customer_id" Type="Order" />
      <Association Name="City_Customer" Member="City" ThisKey="city_id" OtherKey="id" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="is_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="created_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="updated_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="role_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Order" Member="Orders" ThisKey="id" OtherKey="employee_id" Type="Order" />
      <Association Name="Role_Employee" Member="Role" ThisKey="role_id" OtherKey="id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetails" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="product_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="subtotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="Order" ThisKey="order_id" OtherKey="id" Type="Order" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="product_id" OtherKey="id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="employee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="created_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="updated_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Order_OrderDetail" Member="OrderDetails" ThisKey="id" OtherKey="order_id" Type="OrderDetail" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="customer_id" OtherKey="id" Type="Customer" IsForeignKey="true" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="employee_id" OtherKey="id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="available" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="created_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="updated_at" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="type_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="brand_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="id" OtherKey="product_id" Type="OrderDetail" />
      <Association Name="Category_Product" Member="Category" ThisKey="type_id" OtherKey="id" Type="Category" IsForeignKey="true" />
      <Association Name="Category_Product1" Member="Category1" ThisKey="brand_id" OtherKey="id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>